version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8001:8001" # Example port mapping, adjust as needed
