version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/dockerfile
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000" # Example port mapping, adjust as needed

    command: /bin/sh -c "while sleep 1000; do :; done"